### ISSUE TITLE
Sample not working - boot strap error

### ISSUE THREAD

**Issue by karthicktv** [couchbaselabs/couchbase-net-beersample#2]
When attempting to run this example, I get this error: System.AggregateException: 'Could not bootstrap - check inner exceptions for details.'

Can't locate where the config is for the Cluster in order to verify the connection details. Please help.

![image](https://user-images.githubusercontent.com/8471776/40205465-085165e2-5a24-11e8-93d1-505ade771b28.png)

**Comment by MikeGoldsmith** [comment]
Hi @karthicktv 

This Beer example is quite old and is not compatible with Couchbase Server 5.0 because of the new Role Based Access Control (RBAC). In addition, I can see there is bug where the BeerRepository tries to use an unknown View called "all_beers".

A more complete example that demonstrates more of what Couchbase can do is the [Travel Sample](https://github.com/couchbaselabs/try-cb-dotnet).

However, to help keep this repository working I've updated this sample to use the latest version of the Couchbase .NET client (2.5.10, was 2.0.2) and added a simple configuration section to the [web.config](https://github.com/couchbaselabs/couchbase-net-beersample/blob/master/Src/Couchbase.BeerSample.Web/Web.config) that allows a username & password to be used when connecting to the server.

I've also updated the README to describe the configuration changes, and how to add the missing View definition.

Let me know if there is anything else I can help with.

**Comment by karthicktv** [comment]
Thanks for your response @MikeGoldsmith but I also get the similar error on <a href="https://github.com/couchbaselabs/try-cb-dotnet">Travel Sample</a> repository. Looks like ClusterHelper API has issues with .NET but I could be wrong. Maybe you could shed some light on this?

**Comment by MikeGoldsmith** [comment]
What server version have you installed and is it installed locally or elsewhere? (VM / server)

**Comment by karthicktv** [comment]
I am using a Couchbase instance from Azure. Version 
![image](https://user-images.githubusercontent.com/8471776/40303179-ac3c8e80-5ce9-11e8-9254-57d164b3fef7.png)

**Comment by MikeGoldsmith** [comment]
Did you update the Server URIs to point to your Azure instances? eg update URIs in web.config:

```xml
<couchbase username="Administrator" password="password">
  <servers>
    <add uri="http://my-azure-instance:8091" /> <-- update this -->
  </servers>
</couchbase>
```

I'm not too familiar with the Azure instance / network configuration setup, but you'll nee to ensure the Couchbase ports are open and available. This blog may help with getting started: https://blog.couchbase.com/scaling-couchbase-server-azure.

**Comment by karthicktv** [comment]
Sure, I have the Couchbase set up fine for Azure. I have also tried local cluster before Azure but I faced the same issue. I am using the web.config as per this: https://github.com/couchbaselabs/try-cb-dotnet/blob/master/src/try-cb-dotnet/Web.config

Just replaced the CouchbaseServer: <add key="CouchbaseServer" value="http://vm0.server-iehbrrwx6lai2.westeurope.cloudapp.azure.com:8091/pools" />

**Comment by karthicktv** [comment]
Yes, I tried and I still get this error

![image](https://user-images.githubusercontent.com/8471776/40305536-d0160896-5cf2-11e8-93e7-5457ae43b783.png)

**Comment by karthicktv** [comment]
@MikeGoldsmith yes, I tried the Beer sample and it seems to be working but with this error:

![image](https://user-images.githubusercontent.com/8471776/40305716-9acd1af2-5cf3-11e8-883c-c4045f99337e.png)

**Comment by MikeGoldsmith** [comment]
The ViewException is because the "all_beers" view is missing. If you check out the README on the repository homepage you should be good.

FUI The error you're seeing above comes after bootstrap so the sample has connected to your Azure server successfully.

**Comment by karthicktv** [comment]
Yes, I followed and seems fine now. Thanks @MikeGoldsmith for your help. I will review the Travel sample and make some PRs if thats ok?

![image](https://user-images.githubusercontent.com/8471776/40306510-dd470dcc-5cf6-11e8-9151-67bc118c729c.png)

**Comment by MikeGoldsmith** [comment]
Yeah, if you find something that does not work as expected, please create issues / PRs. Thanks.

I'm going to close this issue now, let me know if you need anything else regarding the beer demo not working.
